### ISSUE TITLE
add me plz

### ISSUE THREAD

**Issue by phobicdotno** [MOJOliciousFTW/workshop-github-2024#10] opened 2024-10-25 11:25 UTC

**Comment by kvatsoy** [comment] 2024-10-25 11:27
Add plz

**Comment by Twondy** [comment] 2024-10-25 11:30
Add please

**Comment by Unguided1** [comment] 2024-10-25 11:34
Add plz

**Comment by MOJOliciousFTW** [comment] 2024-10-25 11:35
done.

duplicate of #11

**Closed as completed by MOJOliciousFTW** 2024-10-25 11:35 UTC
Labels: duplicate
